### ISSUE TITLE
incorrect link attachment

### ISSUE THREAD

**Issue by Sagar2366** [collabnix/dockerlabs#108]
Link given for docker compose with secrets is the readme page -> https://github.com/collabnix/dockerlabs/blob/master/intermediate/README.md

**Comment by collabnix** [comment]
@Prashansa-K I know you were planning to write a tutorial for this. Any update?

**Comment by Prashansa-K** [comment]
There was already an existing tutorial for this on the link given below:
https://github.com/collabnix/dockerlabs/blob/master/intermediate/docker-compose/swarm-secrets/README.md

That's why I didn't add any.

**Comment by Prashansa-K** [comment]
Sorry, the above is for swarm secrets. I will add one separately for compose secrets soon. I mistook it earlier and didn't add a new one.

**Comment by collabnix** [comment]
Closing
