### ISSUE TITLE
Broken link Intermediate Track

### ISSUE THREAD

**Issue by pullareddy009** [collabnix/dockerlabs#155]
**Describe the bug**
 Links are broken for Intermediate Track --> Introduction to Docker Networking
**To Reproduce**
1. Go to 'Intermediate Track'
2. Click on 'Understanding Docker Container Networking'
3. See error

**Links**
https://dockerlabs.collabnix.com/intermediate/beginners/dockercontainernetworking.md
https://dockerlabs.collabnix.com/intermediate/beginners/DiffBridgeVsOverlay.md

**Comment by saiyam1814** [comment]
Hi @pullareddy009 THanks for reporting we will check and fix this

**Comment by sangam14** [comment]
> Hi @pullareddy009 THanks for reporting we will check and fix this

@pullareddy009 updating broken links we will get back to you soon ..

**Comment by sangam14** [comment]
@pullareddy009 @saiyam1814 
fixed broken links 
http://dockerlabs.collabnix.com/intermediate/dockercontainernetworking.html
http://dockerlabs.collabnix.com/intermediate/DiffBridgeVsOverlay.html

**Comment by sangam14** [comment]
Thanks for reporting now fixed link @pullareddy009 feel free to report issues

**Comment by pullareddy009** [comment]
Thanks, @sangam14.
