### ISSUE TITLE
Add section Docker Multi-Stage Build

### ISSUE THREAD

**Issue by thiagolsfortunato** [collabnix/dockerlabs#249]
I would like to add a new section, talking about multi-stage-build

my repo: https://github.com/thiagolsfortunato/docker-mult-stage-build

Could I create a new PR on this repo? :sweat_smile:

**Comment by collabnix** [comment]
Yes, go ahead and add it under https://github.com/collabnix/dockerlabs/blob/master/intermediate/README.md#docker-for-developers

I have added it under Intemediate Track.

**Comment by rahulsurwade08** [comment]
Hey @thiagolsfortunato @collabnix I would love to contribute for this under Hacktoberfest. How can I get started?

**Comment by collabnix** [comment]
Hi @RahulSurwade08 You are most welcome.

**Comment by rahulsurwade08** [comment]
Can you assign this issue to me?

**Comment by rahulsurwade08** [comment]
@collabnix Can I get some feedback for the PR?

**Comment by thiagolsfortunato** [comment]
Solved #463
