### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Stephenfang51** [collabnix/dockerlabs#287]
On my Jetson Nano

after enter 
`curl -sSL https://get.docker.com/ | sh`

and it shows the error like

E: The repository 'https://nvidia.github.io/libnvidia-container/ubuntu18.04/arm64  Release' does not have a Release file.
E: The repository 'https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/arm64  Release' does not have a Release file.
E: The repository 'https://nvidia.github.io/nvidia-docker/ubuntu18.04/arm64  Release' does not have a Release file.

How to solve it? Thanks so much

**Comment by collabnix** [comment]
Jetson Nano comes with Docker by default. Are you trying to install the latest version like 19.03??

**Comment by Stephenfang51** [comment]
> Jetson Nano comes with Docker by default. Are you trying to install the latest version like 19.03??

Yes ! just followed your steps to update to 19.03 so that I can use gpu?

**Comment by collabnix** [comment]
All you need is ```sudo apt update``` to pull all the latest update and then curl command should just work.

**Comment by collabnix** [comment]
Can you try:

```
sudo docker run -it --runtime nvidia devicequery
```

directly?

**Comment by Stephenfang51** [comment]
> Can you try:
> 
> ```
> sudo docker run -it --runtime nvidia devicequery
> ```
> 
> directly?

Thanks for your reply
it showed below

```
docker: Error response from daemon : Unknown runtime specified nvidia
```

**Comment by Stephenfang51** [comment]
I followed the following steps before, I didn't noticed that it doesn't support ARM, maybe it's the reason ?

```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update

sudo apt-get install -y nvidia-docker2
sudo pkill -SIGHUP dockerd
```
