### ISSUE TITLE
Dockerfile EXPOSE LAB 11: --format empty on the website

### ISSUE THREAD

**Issue by xinity** [collabnix/dockerlabs#307]
**Describe the bug**
on this lab: https://dockerlabs.collabnix.com/beginners/dockerfile/Lab%2311:EXPOSE_instruction.html
Looking at the inspect section

the website show:
` docker image inspect --format  expose:v1 `
rather than
` $ docker image inspect --format {{.ContainerConfig.ExposedPorts}} expose:v1 `

This might be some kind of the bug regarding the static website generator engine

**Comment by collabnix** [comment]
@saviovettoor Can you have a look?
