### ISSUE TITLE
[DockerLab] no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by ayoub1** [collabnix/dockerlabs#311]
**Describe the bug**
In DockerLab excercice Deployment 101, creating a deployment returns following error : 
error: unable to recognize "nginx-dep.yaml": no matches for kind "Deployment" in version "apps/v1beta2"

**To Reproduce**
1. go to dockerlabs/kubernetes/workshop/Deployment101
2. run "kubectl create -f nginx-dep.yaml"
3. See error

**Expected behavior**
deployment.apps/nginx-deployment should be created

**Comment by ayoub1** [comment]
Happening in a 1.17.0 cluster

**Comment by collabnix** [comment]
@ayoub1 We have migrated Kuberneteslabs to kubelabs.collabnix.com. can you please raise this issue under this new link.

**Comment by collabnix** [comment]
Closing this issue.
