### ISSUE TITLE
ONBUILD page doesn't show how to use ONBUILD

### ISSUE THREAD

**Issue by taylankasap** [collabnix/dockerlabs#322]
**Describe the bug**
ONBUILD page doesn't show how to use the `ONBUILD` command?

**To Reproduce**
1. Go to [ONBUILD page](https://dockerlabs.collabnix.com/beginners/dockerfile/onbuild.html)
2. Look at the code blocks (Dockerfile contents)

**Expected behavior**
`ONBUILD` command should've been used somewhere

**Comment by sangam14** [comment]
Taylankasap.. 😊 Thanks. Let me add code and example soon 🔜

**Comment by sangam14** [comment]
updated https://dockerlabs.collabnix.com/beginners/dockerfile/onbuild.html
