### ISSUE TITLE
SHELL page doesn't show how to use SHELL

### ISSUE THREAD

**Issue by taylankasap** [collabnix/dockerlabs#324]
**Describe the bug**
SHELL page doesn't show how to use the `SHELL` instruction

**To Reproduce**
1. Go to [SHELL page](https://dockerlabs.collabnix.com/beginners/dockerfile/Lab-14-Create-an-image-with-SHELL-instruction.html)
2. Look at the code blocks (Dockerfile contents)

**Expected behavior**
`SHELL` instruction should've been used somewhere

**Comment by sangam14** [comment]
noted we will update soon

**Comment by collabnix** [comment]
@sangam14 Any update?

**Comment by sangam14** [comment]
@taylankasap link fixed !

**Comment by sangam14** [comment]
@collabnix updated dockerfile with `  SHELL` example
