### ISSUE TITLE
Docker Multi Stage Build

### ISSUE THREAD

**Issue by HarsimranjitSingh** [collabnix/dockerlabs#329]
Hi All,

I am understanding the Docker Multi Stage Build which says:

1. We pull an image and execute few command which create few binaries (executable)
2. We extract that binaries from container
3. We run those extracted binaries on new container using a small size image (which support Binaries)

Why DO NOT we keep the binaries and delete remaining stuff there it self in Step 2. It will reduce our image size
If we are able to delete, we DO NOT need to perform Step 3.

**Comment by francilioaraujo** [comment]
> Hi All,
> 
> I am understanding the Docker Multi Stage Build which says:
> 
>     1. We pull an image and execute few command which create few binaries (executable)
> 
>     2. We extract that binaries from container
> 
>     3. We run those extracted binaries on new container using a small size image (which support Binaries)
> 
> 
> Why DO NOT we keep the binaries and delete remaining stuff there it self in Step 2. It will reduce our image size
> If we are able to delete, we DO NOT need to perform Step 3.

Deleting files in images does not work like deleting files in the computer. If you delete a file, it is only deleted on that layer, not on the layers bellow it. So the file is still there in the image, it's just not visible on the upper image.

**Comment by collabnix** [comment]
Closing this issue as there is no further discussion.
