### ISSUE TITLE
Slack join link is expired

### ISSUE THREAD

**Issue by shuuji3** [collabnix/dockerlabs#364]
**Describe the bug**
It seems that the Slack join link is expired. I cannot find a way to join the slack.

**To Reproduce**
1. Go to https://dockerlabs.collabnix.com/kubernetes/kubetools/
2. Click on the "Join Slack" button
4. See the error message: "The link is no longer active" (see the below screenshot)

**Expected behavior**
I can see the webpage to register the account.

**Screenshots**
![Screenshot from 2020-11-22 12-10-37](https://user-images.githubusercontent.com/1425259/99893402-3b4bcb80-2cc3-11eb-88d5-1484ee7673b1.png)

**Additional context**
- The link on https://github.com/collabnix/dockerlabs is also expired.
- This is the same as #64

**Comment by sangam14** [comment]
@shuuji3  thanks ! let me fix it ! 
you can join via https://launchpass.com/collabnix

**Comment by sangam14** [comment]
fixed now @shuuji3 ! thanks !

**Comment by shuuji3** [comment]
@sangam14 Thanks for a quick fix! 😄
