### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by lpgpa** [collabnix/dockerlabs#398]
My students who observed this issue.

When you access https://dockerlabs.collabnix.com/workshop/docker/ in Getting Started with Dockerfile the URL #Lab7 send you to https://dockerlabs.collabnix.com/beginners/dockerfile/Lab-7-Create-an-image-with-EXPOSE-instruction.html but when you practicing Lab#6 in end the URL send you to https://dockerlabs.collabnix.com/beginners/dockerfile/Lab%237:RUN_instruction.html

And congratulation for this material

**Comment by collabnix** [comment]
Good catch. We will fix it.

**Comment by mariosimao** [comment]
I have created a PR to fix this issue
