### ISSUE TITLE
Add Discord Channel 

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/dockerlabs#455]
As Collabnix has discord channel, it would be great to have the following entry in ```_layouts/index.html```:

```
<h3> Join Collabnix Discord Channel </h3>
        
       <iframe src="https://discordapp.com/widget?id=1020180904129335379&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>
```

**Comment by guranshdeol** [comment]
sir is it has to look the same way as twitter timeline shows up?

**Comment by guranshdeol** [comment]
nd also a little button here too!!

![image](https://user-images.githubusercontent.com/91736425/191482576-4bf4154d-11a9-4840-860e-39798c187429.png)
