### ISSUE TITLE
slack invite link is not working

### ISSUE THREAD

**Issue by amitech** [collabnix/dockerlabs#64]
Hi,

This issue is not related with project itself. I want to contribute but not able to join slack channel through provided link. It is showing this error message https://screenshots.firefox.com/tq6fBpPVGFen0ajc/collabnix.slack.com .

**Comment by collabnix** [comment]
Look like the link just got expired. Here's the correct link https://tinyurl.com/y973wcq8

**Comment by amitech** [comment]
Thanks.
